import React from 'react';
import { Catalogue, Partners, ServiceIntroSection, Statistics } from '@/shared';
import { CatalogueCardProps, StatisticsProps } from '@/interfaces';
import { Insights } from '../home';
import styles from './InfrastructureProcurement.module.scss';

const InfrastructureProcurement = () => {
    const statistics: StatisticsProps[] = [
        {
            title: '₦1.54 trillion',
            description: `Projected value of Nigeria's IT outsourcing market in 2025 
            (US $992.6 million x ₦1,555/USD)`,
        },
        {
            title: '₦6.46 trillion',
            description: `Estimated size of Nigeria's cybersecurity market by 2025, 
            based on a US $3.7 billion projection x ₦1,747/USD average rate`,
        },
        {
            title: '₦1.52 trillion',
            description: `Valuation of Nigeria's BPO market in 2023, approximately US $980 million x ₦1,550/USD`,
        },
        {
            title: '₦29 billion',
            description: `Revenue generated by Nigeria's GPU-as-a-Service market in 2024 - US $18.7 million x ₦1,550/USD`,
        },
    ]
    const catalogues: CatalogueCardProps[] = [
        {
            image: '/images/infrastructure_catalogue_1.png',
            text: '',
        },
        {
            image: '/images/infrastructure_catalogue_2.png',
            text: '',
        },
        {
            image: '/images/infrastructure_catalogue_3.png',
            text: '',
        },
        {
            image: '/images/infrastructure_catalogue_4.png',
            text: '',
        },
    ]
  return (
    <div className={styles.capacity_building_section}>
        <div className={styles.divider}></div>
        <div className={styles.capacity_building_content}>
            <ServiceIntroSection
                title='IT Infrastructure Procurement & Supply'
                subtext='We empower African governments with the right infrastructure'
                description='Govtech Africa provides end-to-end IT infrastructure procurement 
                and supply services, ensuring that government agencies have the right hardware, 
                software, and networking solutions to meet their operational needs. 
                Through our network of partners, we are able to select and source the most 
                suitable IT assets, and ensure that agencies receive high-quality, 
                cost-effective solutions that align with their strategic goals. 
                We help government organizations build robust, future-proof IT foundations to 
                drive efficiency, security, and innovation.'
                top_image='/svgs/infrastructure_1.svg'
                bottom_image='/svgs/infrastructure_2.svg'
                description_class={styles.description_class}
            />
            <Statistics list={statistics} />
            {/* <Centerpiece text='Our services ensure that governments can leverage IT 
                investments to improve service delivery, drive innovation, and create 
                long-term value for citizens and stakeholders.' 
            /> */}
            <Catalogue isHeader={false} catalogues={catalogues}
                type='full'
            />
            <Partners />
            <Insights isDivider={false}  />
        </div>
        <div className={styles.divider_green}></div>
    </div>
  )
}

export default InfrastructureProcurement